apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: eureka-2
  name: eureka-2
spec:
  replicas: 1
  selector:
    name: eureka-2
  template:
    metadata:
      labels:
        name: eureka-2
    spec:
      containers:
      - env:
        - name: DSPRING_PROFILES_ACTIVE
          value: peer2
        image: 172.30.187.6:5000/PROJECT/eureka:latest
        imagePullPolicy: Always
        name: eureka-2
        ports:
        - containerPort: 80
          name: eureka-2
          protocol: TCP
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        app2: dsp2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
