apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: eureka-4
  name: eureka-4
spec:
  replicas: 1
  selector:
    name: eureka-4
  template:
    metadata:
      labels:
        name: eureka-4
    spec:
      containers:
      - env:
        - name: DSPRING_PROFILES_ACTIVE
          value: peer4
        image: 172.30.187.6:5000/PROJECT/eureka:latest
        imagePullPolicy: Always
        name: eureka-4
        ports:
        - containerPort: 80
          name: eureka-4
          protocol: TCP
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        app2: dsp2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
